[package]
name = "core-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.95"
web-sys = { version = "0.3.64", features = ['CanvasRenderingContext2d', 'Document', 'Element', 'HtmlCanvasElement', 'Window', 'WheelEvent'] }
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
js-sys = "0.3.72"
wasm-bindgen-futures = "0.4.45"

[lib]
crate-type = ["cdylib"]  # 指定生成 cdylib 类型的动态库

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
